import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMultistepForm } from '../hooks/useMultiStepForm'
import { UserForm } from '../components/UserForm';
import { AddressForm } from '../components/AddressForm';
import { AccountForm } from '../components/AccountForm';

export default function Home() {
  const { currentStepIndex, steps, step, next, back } = useMultistepForm([<UserForm />, <AddressForm />, <AccountForm />]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form>
            <div style={{ position:'absolute', top: '1rem', right: '1rem'}}> {currentStepIndex + 1} / {steps.length}</div>
            {step}
            <div>
                { currentStepIndex !== 0 && <button type='button' onClick={back}>back</button>}
                { currentStepIndex !== steps.length - 1 && <button type='button' onClick={next}>next</button>}
            </div>
        </form>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
